language: node_js

node_js:
  - 'stable'
  - '4'
  - '5'

sudo: false

before_install:
  - npm install -g typings
  - npm install -g codeclimate-test-reporter

after_script:
  - codeclimate-test-reporter < coverage/report-lcov/lcov.info
  - node_modules/.bin/coveralls < coverage/report-lcov/lcov.info

deploy:
  provider: npm
  email: 'devmonk@mediamonks.com'
  api_key:
    secure: 'nkyQm7A/0DDvmDlL4eFOfUmeMb1oBCoyIrCBnha1JbCtWLGEm2G5F9gDEymXGqHSckV00kmUVDDtu9W+HZfAeSq1B54raODjOzXKSKSCuW4GsdeFZcwa4MjcQ7Pl/DKzvmSopTfdEnJ1EbUKplepeeIsm/5yLQyoF1YgJNW8O3lpjk6uYc2tORYTTbF9qGisGr0sU7eljLyNT6oN9zNsDDH9KkAjynetrRe0uugPtnabolgDDZETmRnh9AslngPjp5iT8JQy7eDOFD4RsRzKcLIsp03+z+N3T7UqujrdfJ7xFtGHj7nQD9cFzD1D3dYnYxTnUVnXCyrPUbRu7F0R1ECrdHsNuIucP3cFjhFIKX8gOvXSLSfc9v/eZ/2iU7/aURSONhTmYU+pWSJpuVkmM+HWGOHdj4EwkTeuWIkKHGPdcoyhW6fTOGFnHmD999PnFpxTeRCBo58Muqb7sKAjaLoIwGl8P4ZLTPzt50n2B3iezPCDwdLZJQEDDKUc4bZGW3VYlL9l/nk9WPTsUkCRsIs3gVeE+22e5+3rArpstZGi6rT3TdjEuhg9PeHq5kvAKr6ByGOO9PqLLaVRq1N8dQ8Igbc5gc0utURVXlvyvdp00wwSiPRQNtODX7JE8RAr1IF+Pfq88sGp0WGk4mK1Rtk0ewzOlPpcSTiNyc2RXfE='
  on:
    tags: true
    node: '4'
  skip_cleanup: true

addons:
  code_climate:
    repo_token:
      secure: 'iG1cKxkEW9NHJ0LEvKftiNDkbbJQ8n+2646Mdv9dUs2dRRxUXo5EECTbBxWp4XeF7GOR5ZN3+z07s/YHIUfyne3hzHeRTHEAwVk8NH/ClNqcX8xo+PkxS+sDKDtQD4ETI1gexGXe4gFAphnyywomQ5Co09pKaJl+6yiEtrKm+GBh3coZt+kVdFgXzhdN/j/av+aCw+C0cleps5+dQPOj8l4Bo/45uPF1xQogfQ8xlUS1GqvfUXmoiClTfPw+xNhxlQSLtVuo5RxVgewfxzfx/7zmJI/L8lfOZW8u2fdBAAo4RQSurRab+uugmuGQWErwptVFC/FafzQVyk/HJOph1kwHX0/En+BKnmQHRplcUFv7nkCFbLXl6cF0gv1WWu3NbVRqBWnaeyY2rXppMd600gVA1QtbYhtxcT739Z+HSnjl4cOmh03LtDv5CEyDGZu8DNZ7Hk0nqEvDfl9OlarRpVmKmDnRB5aM+nN1YUIYmrju5d3HBHFvo8mBps8KAMkcFVim1j1TVYgF20Xb6xtNPsXXNTEU1+qdFFq2gLW7C9zj/4HEdiLtgMybeIAWBLozYkYE8D/iH9cDqUyPvXCV/wR0e4uS/jra6Oti48s+Zn1qbL40lPA1X+hqDu6B4+K6dubA00ml8saEmiWCtaBBH71etcUKDLxa6FbNoIrVdD0='
