language: node_js

node_js:
  - 'stable'
  - '4'
  - '5'

sudo: false


before_script:
  - npm install -g typings

#deploy:
#  provider: npm
#  api_key: "YOUR_API_KEY"
#  on:
#    tags: true
#  skip_cleanup: true
